services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: sahibinden
      POSTGRES_PASSWORD: sahibinden
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  eureka-server:
    image: korayguney/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
  apigateway:
    image: korayguney/apigw:latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
  customer-service:
    image: korayguney/customer-service:latest
    container_name: customer-service
    ports:
      - "8080:8080"
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq
  validation-service:
    image: korayguney/validation-service:latest
    container_name: validation-service
    ports:
      - "8081:8081"
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq
  notification-service:
    image: korayguney/notification-service:latest
    container_name: notification-service
    ports:
      - "8082:8082"
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
volumes:
  postgres:
  pgadmin: